// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations usam o endpoint direto (sem pooler) — Prisma Migrate precisa de
    // locks de sessão que não funcionam de forma confiável via pgbouncer/transaction pooling.
    url: process.env["DIRECT_URL"],
  },
});
